version: 2.1

orbs:
  maven: circleci/maven@1.3.0
jobs:
  deploy-heroku:
    docker:
      - image: buildpack-deps:trusty
    executor: heroku/default
    steps:
      - checkout # push/mergeされたコードのチェック
      - run:
          name: Heroku への master のデプロイ
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git develop

workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results
      - deploy-heroku:
        requires:
          - maven/test

        